### PR TITLE
Add a console window to show output of slow git commands

### PR DESCRIPTION
**Pull request by ten3roberts**
This PR adds a verbosity option to processes. Verbose processes will show both stdout and stderr to the console, while non-verbose ones, like `git log` and `git rev-parse` will only show stderr. If a command takes more than `console_timeout` time and an interactive target, such as a commit buffer has not been reached, the console will open, showing what is happening.

This happens for slow commits hooks, or pre-commit hooks which fails, allowing the user to very easily see what ran, what is said, and why it is taking so long.

This is slightly akin to the already existing log, but a more user facing and realtime approach.

This implements the features discussed in #339

### CODE REVIEW

**Comment by ten3roberts** [comment]
It feels great to be able to rebase and remove tmp commits before opening a pr. No more messy commit history :tada:

**Comment by ten3roberts** [comment]
Let me know how this feature could be improved, and if there should be a statusline indicator or similar as well

**Comment by gegoune** [comment]
@ten3roberts My commit just failed after writing and saving commit message. pre-commit's output with all 'passes' was present in the terminal with line at the end:

```
  env: python: No such file or directory
```
This is not happening in regular terminal with `git commit` and also wasn't happening on master branch. Can test it more if you point me in the right direction.

Another small point - output wasn't coloured, is it possible to make it look the same as in regular terminal?

**Comment by ten3roberts** [comment]
Yes.

Those are exactly the two painpoints I've been encountering.

Colors are easy, we just need to enable pty.


The python env issue is because `libuv.spawn` doesn't merge the env.

Using the `jobstart` api would allow for both pty behavior, env merging, and sync/blocking calls. Currently, jobstart are used for call_blocking, and interactive_git_command (git push), while `uv.spawn` is used for the rest of the background commands.

The only thing I've found is that jobstart replaces nulls with newlines, which means that the `-z` flag used in git status does not work. Have not been able to find out why jobstart does this.

@TimUntersberger is it ok to replace the process.lua usage of libuv.spawn with jobstart, which would also allow for more code reuse, as the console command can't be used for call_sync/blocking, and the git error logs aren't working for the `to_job` cli commands.

If so, I can include the change to jobstart in this pr

**Comment by ten3roberts** [comment]
The python issue is related to the environment not being merged à'la #353, #356, and #347, which is again fixed by jobstart, which was used previously by `interactive_git_command` rather than the `.call()` which is used for others

**Comment by TimUntersberger** [comment]
Wow this is really cool! Thank you for your work again! Do you want to be added as a collaborator?

> is it ok to replace the process.lua usage of libuv.spawn with jobstart? It would allow for more code reuse, as the console command can't be used for call_sync/blocking, and the git error logs aren't working for the to_job cli commands.

👍

**Comment by ten3roberts** [comment]
Another preference discussion. The console window is currently global for all commits with headers, showing each git command. Non verbose commands which do not output anything to stderr are not shown.

Because it is global you can see the context that lead up to the failing command, such as a in progress rebase followed by a pull.

Should I keep it this way or do one console window per command? The advantage with keeping it global is that a background buffer won't need to be created for each git command in vain in case it may output. The disadvantage is that it could become slightly more cluttered if many commands are marked as verbose.

The console window is a tty terminal, so colors and all should work, we just need to tell the subprocess that is has access to a pty (which will come with jobstart migration).

> Wow this is really cool! Thank you for your work again! Do you want to be added as a collaborator?
> 
> > is it ok to replace the process.lua usage of libuv.spawn with jobstart? It would allow for more code reuse, as the console command can't be used for call_sync/blocking, and the git error logs aren't working for the to_job cli commands.
> 
> +1

It would be great to be added as a collaborator :smile:

**Comment by ten3roberts** [comment]
There is now a keybind `#` to open the console buffer. The log buffer is still useful for viewing the execution order of commands, and what has been done, while the console is mostly useful to view what went wrong, or a failed precommit hook

**Comment by ten3roberts** [comment]
I have now finished the console feature, as well as making some refactors and dead clone cleanups. Most notably, removal of the two different process/job apis, as wel as merging the `interactive_git_command` to also use the same api instead of a custom jobstart invocation, which isn't handled by the logs.

Let me know what you think, and if you encounter any issues

**Comment by TimUntersberger** [comment]
Thank you for your work! I also added you as a collaborator now.

**Pull request merged**
