### PR TITLE
fix(process): remove sending extra codes

### LINKED ISSUE #382: Color codes in git output
### Description

Follow up of #379 , sort of.

#380 removed the `^D^H^H` prefixes to "everything" on Linux for me (which is awesome)

On macOS, they're not quite gone yet. They've changed from `^D^H^H` to `^D`.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

### Operating system and version

macOS 13

### Steps to reproduce

1. nvim -u minimal.lua in a git repo
2. :Neogit
3. observe `^D` in unpulled, unmerged commits and at the start of the commit message on Head: and Push:

### Expected behavior

No `^D` characters

### Actual behavior

image

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

### PR DESCRIPTION
**Pull request by danilshvalov**
Fixes #382, #384

### CODE REVIEW

**Comment by TimUntersberger** [comment]
This is supposed to be a fix for a bug introduced in https://github.com/TimUntersberger/neogit/commit/541d7a1dc643b364eeecaa62f68b57f4c738d8b9. @ten3roberts

**Comment by ten3roberts** [comment]
While writing the original code, the chanclose did not "close" stdin on the child process point of view.

This means that a pager will keep waiting for page down, or that input prompts will keep waiting for input.

The solution was to send EOT. I then disabled the git pager, but removing the EOT may cause some commands to never finish.

But yes, it can definitely be removed, and if issues crop up about freezing/unresponsive or long commands in terms of async, it may be due to it.

I am currently experiencing solving issue #387 which is caused by the pty emulation causing git to not show the whole file, but stops after a while. Setting `pty =false` solves the incorrect diffs, though will cause precommits to not emit color codes.

I am not sure if it is due to a vim/neovim issue for jobstart and on_stdout, or on gits side when running in a pty.

I am thinking the best of both worlds is to only have `commit`, `rebase`, `push`, and `pull` use `pty=true` by making it an option in the cli builder like `show_stdout`.

Regarding the issue of the output not being captured in full; I have discovered a similar issue in https://github.com/ten3roberts/recipe.nvim where a `fn.termopen` will not show the last output of a command if it terminates immediately afterwards, like a testing command.

**Comment by ten3roberts** [comment]
@TimUntersberger 

How ok are you that I review and merge some PRs that aren't controversial?

I.e; do you give consent that I handle merging and issue closings?

**Comment by TimUntersberger** [comment]
> @TimUntersberger
> 
> How ok are you that I review and merge some PRs that aren't controversial?
> 
> I.e; do you give consent that I handle merging and issue closings?

Go ahead :)

**Comment by MartyBeGood** [comment]
no more stray `^D`s on macOS, no change in behavior on Linux! 👍

**Pull request merged**
