### PR TITLE
feat: Update diffview integration.

### PR DESCRIPTION
**Pull request by sindrets**
Hello @TimUntersberger! I hope you're doing well.

We're working on some [big changes in diffview](https://github.com/sindrets/diffview.nvim/pull/235) in preparation of implementing support for multiple VCS. This PR brings some small adjustments that will be necessary for the diffview integration in Neogit to work after we have merged that refactor.

This also enables diffviews created from Neogit to use the merge-tool in Diffview.nvim. (A note on that: it seems like merge conflicts in Neogit shows up in the "Untracked" section. This seems unintentional, no?)

I'll remove the draft status of this PR once we merge the changes on our end :)

### CODE REVIEW

**Comment by gegoune** [comment]
@sindrets gentle nudge in case this PR slipped your mind. With refactoring merged in on your side, integration is broken now.

**Comment by sindrets** [comment]
@gegoune It didn't slip my mind, the PR is open for review. I don't have permission to merge, if that's what you mean. I recommend that you just roll back diffview until this is merged. Sorry for the inconvenience.

**Comment by gegoune** [comment]
@sindrets Sincere apologies, I only meant changing state from draft - weirdly I have missed that you did that already!

**Comment by TimUntersberger** [comment]
@sindrets Thank you for your work! :)

**Pull request merged**
