### PR TITLE
Merge upstream - 7

### PR DESCRIPTION
**Pull request by CKolkey**

### CODE REVIEW

**Comment by ten3roberts** [comment]
Thank you for rebasing the branch.

Hopefully I didn't cause too much mess in fixing the conflicts on the Neogit/ckolkey branch to keep it up to date to Neogit/master.

**Comment by CKolkey** [comment]
No worries, I think the confusion came from the commits you made to ckolkey but not to master. Not an issue, I just didn't notice 😅 In any case, I'll get this in ship-shape tomorrow

**Comment by ten3roberts** [comment]
Yes, merges are tricky because you end up with commits from the target branch sprinkled ontop, which brings more confusion when you add more commits yourself, so the history looks like this:

- my feature
- my feature
- from main from someone else
- from main from someone else
- my feature

I prefer rebase but it isn't always possible for public branches

**Comment by CKolkey** [comment]
Agreed. Well... third time is the charm: https://github.com/TimUntersberger/neogit/pull/531

**Pull request closed without merging**
